version: '3.4'

services:
  dotfiles:
    image: dotfiles
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        # base|nodejs
        BUILD_TARGET: ${BUILD_TARGET:-base}
    env_file: .env
    environment:
      GIT_AUTHOR_NAME: ${GIT_NAME}
      GIT_AUTHOR_EMAIL: ${GIT_EMAIL}
      GIT_COMMITTER_NAME: ${GIT_NAME}
      GIT_COMMITTER_EMAIL: ${GIT_EMAIL}
      GITHUB_USERNAME:
      # only token
      GITHUB_PASSWORD:
    volumes:
      - workspace:/workspace
    tty: true

volumes:
  workspace:
