#!/usr/bin/env sh

COMMIT_MSG_FILE=$1
BRANCH_NAME=$(git branch | \grep '*' | sed 's/* //')

if [ $BRANCH_NAME != '(no branch)' ]; then
    {
        echo
        echo '# Logs'
        echo '#'
        git log -30 --format=%s | sed 's/^/# /'
    } >> $COMMIT_MSG_FILE
fi
