#!/bin/sh

xargs -I{} code --install-extension {} << EOS
albert.TabOut
alefragnani.project-manager
bierner.markdown-mermaid
christian-kohler.path-intellisense
dbaeumer.vscode-eslint
eamodio.gitlens
esbenp.prettier-vscode
formulahendry.auto-rename-tag
GitHub.remotehub
GitHub.vscode-pull-request-github
hbenl.vscode-test-explorer
hediet.vscode-drawio
humao.rest-client
jock.svg
liviuschera.noctis
ms-azuretools.vscode-docker
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode-remote.remote-wsl
ms-vscode-remote.vscode-remote-extensionpack
ms-vscode.cpptools
ms-vscode.test-adapter-converter
oderwat.indent-rainbow
PKief.material-icon-theme
shd101wyy.markdown-preview-enhanced
streetsidesoftware.code-spell-checker
usernamehw.errorlens
vscodevim.vim
wayou.vscode-todo-highlight
webfreak.debug
yanai101.css-var-hint
yzhang.markdown-all-in-one
EOS
