#!/bin/sh

xargs -I{} code --install-extension {} << EOS
albert.TabOut
alefragnani.project-manager
christian-kohler.path-intellisense
dbaeumer.vscode-eslint
donjayamanne.githistory
elmTooling.elm-ls-vscode
esbenp.prettier-vscode
GitHub.remotehub
GitHub.vscode-pull-request-github
hbenl.vscode-test-explorer
hediet.vscode-drawio
humao.rest-client
jock.svg
kosz78.nim
liviuschera.noctis
ms-azuretools.vscode-docker
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode-remote.remote-wsl
ms-vscode-remote.vscode-remote-extensionpack
ms-vscode.cpptools
ms-vscode.test-adapter-converter
PKief.material-icon-theme
shd101wyy.markdown-preview-enhanced
streetsidesoftware.code-spell-checker
vivaxy.vscode-conventional-commits
vscodevim.vim
wayou.vscode-todo-highlight
webfreak.debug
yanai101.css-var-hint
yzhang.markdown-all-in-one
EOS
