#!/bin/sh

xargs -I{} code --install-extension {} << EOS
albert.TabOut
alefragnani.Bookmarks
alefragnani.project-manager
andys8.jest-snippets
bierner.markdown-mermaid
christian-kohler.path-intellisense
dbaeumer.vscode-eslint
eamodio.gitlens
esbenp.prettier-vscode
firsttris.vscode-jest-runner
formulahendry.auto-rename-tag
GitHub.remotehub
hbenl.vscode-test-explorer
hediet.vscode-drawio
humao.rest-client
jock.svg
liviuschera.noctis
ms-azuretools.vscode-docker
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode-remote.remote-wsl
ms-vscode-remote.vscode-remote-extensionpack
ms-vscode.cpptools
ms-vscode.remote-explorer
ms-vscode.remote-repositories
ms-vscode.remote-server
ms-vscode.test-adapter-converter
ms-vsliveshare.vsliveshare
ms-vsliveshare.vsliveshare-pack
PKief.material-icon-theme
shd101wyy.markdown-preview-enhanced
streetsidesoftware.code-spell-checker
usernamehw.errorlens
VisualStudioExptTeam.intellicode-api-usage-examples
VisualStudioExptTeam.vscodeintellicode
VisualStudioExptTeam.vscodeintellicode-completions
vscodevim.vim
wayou.vscode-todo-highlight
webfreak.debug
yzhang.markdown-all-in-one
EOS
