[revisions]
revset = "::"

[[actions]]
name = "show oplog diff patch"
lua = '''
diff.show(jj("op", "show",  context.operation_id(), "--patch", "--color", "always"))
'''
[[bindings]]
action = "show oplog diff patch"
key = "s"
scope = "oplog"

[[actions]]
name = "commit and advance bookmark"
lua = '''
jj_interactive("util", "exec",  "--", "bash", "-c", "jj edit " .. context.change_id() .. " && jj commit && jj bookmark advance")
'''
[[bindings]]
action = "commit and advance bookmark"
key = "C"
scope = "revisions"

[preview]
revision_command = ["show", "--color", "always", "-r", "$change_id", "--config", "ui.diff-formatter=delta-non-split"]
