#!/usr/bin/env sh

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
BRANCH_NAME=$(git branch | \grep '*' | sed 's/* //')

# append logs as comments if it is not rebasing or amending
if [ "$BRANCH_NAME" != '(no branch)' ] && [ "$COMMIT_SOURCE" != 'commit' ] && [ "$COMMIT_SOURCE" != 'message' ]; then
    {
        echo
        echo '# Logs'
        echo '#'
        git log -30 --format=%s | sed 's/^/# /'
    } >> $COMMIT_MSG_FILE
fi

LOCAL_HOOK="$(git rev-parse --show-toplevel)/.git/hooks/$(basename $0)"

if [ -x "$LOCAL_HOOK" ]; then
  "$LOCAL_HOOK" "$@"
fi
